# Generated by Django 4.0 on 2022-02-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='full_name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default='Female', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='languages',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='license_certification',
            field=models.JSONField(blank=True),
        ),
    ]
