# Generated by Django 4.0 on 2022-02-27 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_full_name_userprofile_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAppliedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('applied_job_id', models.IntegerField()),
            ],
        ),
    ]
