# Generated by Django 4.0 on 2022-02-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0006_alter_jobposting_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='department',
            field=models.CharField(default='Engineering', max_length=255),
            preserve_default=False,
        ),
    ]
