# Generated by Django 4.0 on 2022-02-25 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('recruiting', '0007_jobposting_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_link', models.URLField(blank=True, db_index=True, max_length=255, unique=True, verbose_name="Link to applicant's resume!")),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Waiting for materials', 'Waiting for materials'), ('In Interview', 'In Interview'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=255)),
                ('expected_salary', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiting.jobposting')),
            ],
        ),
    ]
