# Generated by Django 4.0 on 2022-02-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0009_alter_jobapplication_resume_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_image',
            field=models.FileField(blank=True, upload_to='avatars/'),
        ),
    ]
