# Generated by Django 4.0 on 2022-03-06 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('recruiting', '0010_profile_avatar_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communication',
            name='date',
        ),
        migrations.RemoveField(
            model_name='communication',
            name='interview',
        ),
        migrations.AlterField(
            model_name='communication',
            name='sender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.CreateModel(
            name='InterviewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('started', 'Started'), ('internal_comment', 'Internal Comment'), ('file_attached', 'File Attached'), ('assignment', 'Assignment')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiting.interview')),
            ],
        ),
        migrations.AddField(
            model_name='communication',
            name='event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiting.interviewevent'),
        ),
    ]
