# Generated by Django 4.0 on 2022-03-06 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0011_remove_communication_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewFileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recruiting.interviewevent')),
            ],
        ),
    ]
