# Generated by Django 4.0 on 2022-03-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0013_remove_interviewevent_interview_interviewround_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewround',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='expected_salary',
            field=models.IntegerField(null=True),
        ),
    ]
