# Generated by Django 4.0 on 2022-03-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0015_alter_communication_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewround',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=25),
        ),
    ]
