# Generated by Django 4.0 on 2022-03-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0016_interviewround_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewround',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
