# Generated by Django 4.0 on 2022-03-12 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0017_interviewround_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewfileattachment',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='recruiting.interviewevent'),
        ),
    ]
