# Generated by Django 4.0 on 2022-03-12 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('recruiting', '0018_alter_interviewfileattachment_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewRoundAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='auth.user')),
                ('interview_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='recruiting.interviewround')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewRoundAssignmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='recruiting.interviewroundassignment')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recruiting.interviewevent')),
                ('interview_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='recruiting.interviewround')),
            ],
        ),
    ]
