# Generated by Django 4.0 on 2022-03-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0019_interviewroundassignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewroundassignmentevent',
            name='interview_round',
        ),
    ]
