# Generated by Django 4.0 on 2022-03-12 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0020_remove_interviewroundassignmentevent_interview_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewroundassignmentevent',
            name='assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='recruiting.interviewroundassignment'),
        ),
    ]
