# Generated by Django 4.0 on 2022-03-12 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0021_alter_interviewroundassignmentevent_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewevent',
            name='interview_round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='recruiting.interviewround'),
        ),
        migrations.AlterField(
            model_name='interviewround',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='recruiting.interview'),
        ),
        migrations.AlterField(
            model_name='interviewroundassignmentevent',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_event', to='recruiting.interviewevent'),
        ),
    ]
